services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: book_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d book_manager"]
      interval: 10s
      timeout: 5s
      retries: 5

  db_migrate:
    image: flyway/flyway:10-alpine
    container_name: flyway_migrate
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - migrate
    volumes:
      - ./migration:/flyway/sql
    command: -url=jdbc:postgresql://db:5432/book_manager -user=myuser -password=mypassword migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://db:5432/book_manager
      FLYWAY_USER: myuser
      FLYWAY_PASSWORD: mypassword

  db_rebuild:
    image: flyway/flyway:10-alpine
    container_name: flyway_rebuild
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - rebuild
    volumes:
      - ./migration:/flyway/sql
    entrypoint: ["/bin/sh", "-c"]
    command: ["flyway -url=jdbc:postgresql://db:5432/book_manager -user=myuser -password=mypassword clean && flyway -url=jdbc:postgresql://db:5432/book_manager -user=myuser -password=mypassword migrate"]
    environment:
      FLYWAY_URL: jdbc:postgresql://db:5432/book_manager
      FLYWAY_USER: myuser
      FLYWAY_PASSWORD: mypassword
      FLYWAY_CLEAN_DISABLED: "false"

volumes:
  postgres_data:
