/*
 * This file is generated by jOOQ.
 */
package com.book_manager.jooq.enums;


import com.book_manager.jooq.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum BookPublicationStatus implements EnumType {

    NOT_PUBLISHED("NOT_PUBLISHED"),

    PUBLISHED("PUBLISHED");

    private final String literal;

    private BookPublicationStatus(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "book_publication_status";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static BookPublicationStatus lookupLiteral(String literal) {
        return EnumType.lookupLiteral(BookPublicationStatus.class, literal);
    }
}
