/*
 * This file is generated by jOOQ.
 */
package com.book_manager.jooq;


import com.book_manager.jooq.tables.Author;
import com.book_manager.jooq.tables.Book;
import com.book_manager.jooq.tables.BookAuthor;
import com.book_manager.jooq.tables.FlywaySchemaHistory;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>public.book</code>.
     */
    public static final Book BOOK = Book.BOOK;

    /**
     * The table <code>public.book_author</code>.
     */
    public static final BookAuthor BOOK_AUTHOR = BookAuthor.BOOK_AUTHOR;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;
}
