/*
 * This file is generated by jOOQ.
 */
package com.book_manager.jooq.tables.records;


import com.book_manager.jooq.enums.BookPublicationStatus;
import com.book_manager.jooq.tables.Book;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookRecord extends UpdatableRecordImpl<BookRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.book.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.book.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.book.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.book.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.book.price</code>.
     */
    public void setPrice(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.book.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.book.publication_status</code>.
     */
    public void setPublicationStatus(BookPublicationStatus value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.book.publication_status</code>.
     */
    public BookPublicationStatus getPublicationStatus() {
        return (BookPublicationStatus) get(3);
    }

    /**
     * Setter for <code>public.book.version</code>.
     */
    public void setVersion(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.book.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.book.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.book.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.book.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.book.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookRecord
     */
    public BookRecord() {
        super(Book.BOOK);
    }

    /**
     * Create a detached, initialised BookRecord
     */
    public BookRecord(Long id, String title, Integer price, BookPublicationStatus publicationStatus, Integer version, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Book.BOOK);

        setId(id);
        setTitle(title);
        setPrice(price);
        setPublicationStatus(publicationStatus);
        setVersion(version);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
